model:
  - tabNTL
trainer:
  - NTL_active
network:
  - tabNTL
device:
  - cuda
learning_rate:
  - 0.001
training_epochs:
  - 100
train_method:
  - loe_est
query_method:
  - kmeans
enc_nlayers:
  - 3
num_trans:
  - 9
trans_nlayers:
  - 3
trans_type:
  - residual
loss:
  - DCL
batch_norm:
  - False
loss_temp:
  - 0.1
l2:
  - 0.
optimizer:
  - Adam
scheduler:
  -
    class: StepLR
    args:
      step_size: 200
      gamma: 0.5
early_stopper:
  -
    class: Patience
    args:
      patience: 100
      use_train_loss: True

shuffle:
  - True
num_repeat:
  - 5
save_scores:
  - False
result_folder:
  - RESULTS_active/